### ISSUE TITLE
Display Latency Issue

### ISSUE THREAD

**Issue by Jak-Kav** [Kav-Simulations/MobiFlight-KavSimulations#20]
An external developer has reported possible latency with the LCDs when using MobiFlight.
They report that in the HT1621 base library, there are delays of 20ms, and this is causing the issue.

- - - - -

### Possible fix provided:
Reduce the time to 30 us, which works perfectly and is much smoother.
- `HT1621::writeBits`
- `HT1621::writeBitsReverse`

**Comment by elral** [comment]
Hmhm, what I can see in the code is a delay of 20 microseconds already, not milliseconds -> `delayMicroseconds(20);`

According the datasheet max speed for writing data is 300kHz on 5V and 150kHz on 3V. Assuming 150Khz would mean two delays of 4 micorseconds. The code shows 3 delays I am wondering about.
Might be potential for more optimazations.

**Comment by Jak-Kav** [comment]
Yes, I see what you mean.
For context, these are the screenshots that were sent to me, with the second picture being what the developer has done. They state that this has given them a performance increase. This will need a more detailed look, as if they are both microseconds, then the developer might actually be **increasing** the delay from 20, to 30.

![libraryarduino](https://github.com/Kav-Simulations/MobiFlight-KavSimulations/assets/71826077/1fbe88b1-8e6d-42bd-9d70-bc288bdc5bb4)

![librarygreg](https://github.com/Kav-Simulations/MobiFlight-KavSimulations/assets/71826077/29709de3-3cc2-471a-91b8-c6ee38ade98e)

**Comment by elral** [comment]
Yes, compared to the actual library it looks that they have **increased** the time. The question is what they had before? Maybe by fault a delay of 20 milliseconds? Seems that they have another processor architecture or at least another IDE.
This would explain the high latency.

I still think the first delay is not required. This would set CLK and data to there level at the same time, after a delay CLK is set to HIGH, and after another delay back to LOW. As the data is read on the rising edge there should be enough time to stbilize the data output.
Assuming a 3V supply the min. time of the pulse width must be 3.34 microseconds according the datasheet. That would mean a `delay_us(4)` should work after setting the data line and after setting the CLK line to LOW respectively to HIGH. The first delay after setting the CLK line is not required.

**Comment by elral** [comment]
> Maybe by fault a delay of 20 milliseconds?

One more thinking about this, it can't be a delay of 20ms within the writeBits() functions, would be way too long.

But I found the library Arduino links to: [https://github.com/valerionew/ht1621-7-seg](https://github.com/valerionew/ht1621-7-seg)

And they use also the delay of 4 microseconds: [ht1621-7-seg/src/HT1621.cpp at master · valerionew/ht1621-7-seg (github.com)](https://github.com/valerionew/ht1621-7-seg/blob/master/src/HT1621.cpp#L71-L86)

**Comment by Jak-Kav** [comment]
Yes, interesting.
I haven't had a chance to look at this pproperly, but I will try and tkae a look next week where I can.
Definatley something needs to change either way by the looks of it.
