### ISSUE TITLE
Pin input in wrong order

### ISSUE THREAD

**Issue by Jak-Kav** [Kav-Simulations/MobiFlight-KavSimulations#22]
When selecting pins for a custom device, the order of input is confusing.
The data pin is first, when it should be last.

This should be able to be fixed by adapting the device JSON files to show the correct order.

**Comment by elral** [comment]
@Jak-Kav If you change the order in the device.json files, then the new order has to be considered in the FW too.

**Comment by elral** [comment]
```
params = strtok_r(parameter, "|", &p);
_pin1  = atoi(params);
params = strtok_r(NULL, "|", &p);
_pin2  = atoi(params);
params = strtok_r(NULL, "|", &p);
_pin3  = atoi(params);
```

`_FCU_LCD->attach(_pin2, _pin3, _pin1);`

`KAV_A3XX_FCU_LCD(uint8_t CS, uint8_t CLK, uint8_t DATA)`

**Comment by JaimeLeon2** [comment]
the pins on the PCB are VCC GND Data CLK and CS last.
However, the order in the Mobiflight device config is Data CS CLK.
This little change in order caused me to configure the wiring incorrectly the first time.
